/* Generated by scripts/generate-app-icon.mjs — do not edit by hand. */
export const brandMarkViewBox = "0 0 1024 1024";

export const brandMarkTile = {
  x: 81,
  y: 81,
  width: 862,
  height: 862,
  rx: 225,
  ry: 225,
} as const;

export const brandMarkPath = "M 713.842 667.488 A 241.36 241.36 0 1 1 713.842 356.512 L 631.431 425.926 A 133.61 133.61 0 1 0 631.431 598.074 Z";
